/*
 * LEGAL PAGES — Disclaimer, Privacy Policy, Terms of Use
 * Professional fintech-grade legal content
 */
import { motion } from "framer-motion";
import { Shield, Lock, FileText, ArrowLeft } from "lucide-react";
import { Link } from "wouter";

const fadeIn = { initial: { opacity: 0, y: 20 }, animate: { opacity: 1, y: 0 }, transition: { duration: 0.5 } };

function LegalPageWrapper({ title, icon: Icon, children }: { title: string; icon: React.ElementType; children: React.ReactNode }) {
  return (
    <div className="max-w-4xl mx-auto">
      <motion.div {...fadeIn}>
        <Link href="/app" className="inline-flex items-center gap-2 text-sm text-slate-500 hover:text-cyan-600 mb-8 transition-colors">
          <ArrowLeft className="w-4 h-4" />
          Back to Dashboard
        </Link>

        <div className="flex items-center gap-4 mb-8">
          <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-cyan-500/10 to-teal-500/10 flex items-center justify-center border border-cyan-500/20">
            <Icon className="w-6 h-6 text-cyan-600" />
          </div>
          <div>
            <h1 className="text-2xl font-bold font-display text-slate-900 tracking-tight">{title}</h1>
            <p className="text-sm text-slate-500 font-body mt-0.5">Last updated: March 2026</p>
          </div>
        </div>

        <div className="bg-white rounded-2xl border border-slate-200 p-8 md:p-10 shadow-sm">
          <div className="prose prose-slate max-w-none prose-headings:font-display prose-headings:tracking-tight prose-p:font-body prose-p:text-[15px] prose-p:leading-relaxed prose-li:font-body prose-li:text-[15px]">
            {children}
          </div>
        </div>

        <div className="mt-8 text-center text-xs text-slate-400 font-body">
          <p>&copy; {new Date().getFullYear()} Tatiana Podobivskaia &middot; Atlantis University, Miami FL</p>
        </div>
      </motion.div>
    </div>
  );
}

export function DisclaimerPage() {
  return (
    <LegalPageWrapper title="Disclaimer" icon={Shield}>
      <h2>Academic Research Prototype</h2>
      <p>
        TradeScreen AI is an academic research prototype developed at Atlantis University. This system is designed
        for educational and research purposes only and is <strong>not a commercial compliance tool</strong>.
      </p>

      <h2>No Legal or Compliance Advice</h2>
      <p>
        The information and screening results provided by TradeScreen AI do not constitute legal, financial,
        or compliance advice. This system is not a substitute for professional legal or compliance counsel.
        All results should be verified by qualified compliance professionals before any business decisions are made.
      </p>

      <h2>Accuracy and Completeness</h2>
      <p>
        While TradeScreen AI uses data from publicly available government sanctions databases (OFAC SDN, EU Consolidated,
        UN Security Council, UK OFSI), we make no warranties regarding the accuracy, completeness, or timeliness of the
        screening results. Sanctions lists are updated periodically, and there may be delays between official list updates
        and their reflection in this prototype.
      </p>

      <h2>AI-Generated Analysis</h2>
      <p>
        The GPT-4o deep analysis feature provides AI-assisted risk assessments. These assessments are generated by
        artificial intelligence and may contain errors, hallucinations, or incomplete analysis. AI-generated content
        should always be reviewed by a qualified human analyst.
      </p>

      <h2>Limitation of Liability</h2>
      <p>
        The developer and Atlantis University shall not be held liable for any damages, losses, or consequences
        arising from the use of this prototype, including but not limited to reliance on screening results,
        AI-generated analysis, or any other output of this system.
      </p>
    </LegalPageWrapper>
  );
}

export function PrivacyPolicyPage() {
  return (
    <LegalPageWrapper title="Privacy Policy" icon={Lock}>
      <h2>Data Processing</h2>
      <p>
        TradeScreen AI is designed with privacy as a core principle. This prototype provides AI-assisted analysis
        to support human review. All screening data is processed locally in the browser wherever possible.
      </p>

      <h2>No Data Collection</h2>
      <p>
        No vendor names, screening results, or uploaded documents are stored, transmitted to external servers,
        or retained after the session ends. We do not collect, store, or sell any personal information or
        screening queries entered into this system.
      </p>

      <h2>Sanctions Data Sources</h2>
      <p>
        All sanctions list data is sourced from publicly available government databases:
      </p>
      <ul>
        <li><strong>OFAC SDN</strong> — U.S. Department of the Treasury, Office of Foreign Assets Control</li>
        <li><strong>EU Consolidated</strong> — European Union Consolidated Financial Sanctions List</li>
        <li><strong>UN Security Council</strong> — United Nations Security Council Consolidated List</li>
        <li><strong>UK OFSI</strong> — UK Office of Financial Sanctions Implementation</li>
      </ul>

      <h2>AI Processing</h2>
      <p>
        When the GPT-4o deep analysis feature is used, query data may be sent to Azure OpenAI services for processing.
        This data is not retained by the AI service beyond the immediate processing session and is subject to
        Microsoft Azure's data processing agreements.
      </p>

      <h2>Browser Storage</h2>
      <p>
        This prototype may use browser local storage for user preferences (such as theme settings and screening
        thresholds). This data remains entirely on your device and is never transmitted externally.
      </p>

      <h2>Contact</h2>
      <p>
        For questions about this privacy policy, please contact the researcher through the About page.
      </p>
    </LegalPageWrapper>
  );
}

export function TermsOfUsePage() {
  return (
    <LegalPageWrapper title="Terms of Use" icon={FileText}>
      <h2>Acceptance of Terms</h2>
      <p>
        By accessing and using TradeScreen AI, you acknowledge that this is an academic research prototype
        and agree to the following terms of use.
      </p>

      <h2>Educational Use Only</h2>
      <p>
        TradeScreen AI is developed for educational and research purposes at Atlantis University.
        This system is <strong>not intended for commercial use</strong> or as a replacement for professional
        compliance screening tools. Users should not rely on this prototype for actual sanctions compliance decisions.
      </p>

      <h2>Permitted Use</h2>
      <p>You may use TradeScreen AI for:</p>
      <ul>
        <li>Academic research and educational exploration</li>
        <li>Understanding sanctions screening methodologies</li>
        <li>Evaluating AI-assisted compliance analysis approaches</li>
        <li>Studying Cyrillic transliteration in compliance contexts</li>
      </ul>

      <h2>Prohibited Use</h2>
      <p>You may <strong>not</strong> use TradeScreen AI for:</p>
      <ul>
        <li>Commercial sanctions compliance screening</li>
        <li>Making actual business or financial decisions based solely on screening results</li>
        <li>Circumventing or evading sanctions regulations</li>
        <li>Any illegal or unauthorized purpose</li>
      </ul>

      <h2>Intellectual Property</h2>
      <p>
        The TradeScreen AI prototype, including its design, code, and methodology, is the intellectual property
        of the researcher. The underlying sanctions data is sourced from public government databases and remains
        the property of the respective issuing authorities.
      </p>

      <h2>Modifications</h2>
      <p>
        These terms may be updated at any time without prior notice. Continued use of the prototype after
        changes constitutes acceptance of the modified terms.
      </p>
    </LegalPageWrapper>
  );
}
